sudo:
  false

language:
  python

python:
  - 2.7
  # - 3.3
  # - 3.4
  - 3.5
  - 3.6

before_install:
  - openssl aes-256-cbc -K $encrypted_c877ec287e14_key -iv $encrypted_c877ec287e14_iv -in .credentials.json.enc -out .credentials.json -d

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install

script:
  - make version
  - make test
